-- ============================================================
-- 012. 로켓그로스 상품별 실제 개당 수수료·입출고비·보관비 — 이력 스냅샷
--
-- WING 재고현황(inventory-health-dashboard/search) API가 주는 상품별 실제값
-- (카테고리 요율표 추정이 아니라 쿠팡이 그 상품에 직접 매긴 값)을 저장한다.
-- docs/api-notes.md 4-4-6 참조.
--
-- **덮어쓰지 않고 매번 새 행으로 쌓는다(이력 테이블)** — 가격을 바꾸면 개당
-- 수수료/입출고비가 같이 바뀌는데, 가격 변경 "전"에 팔린 것은 변경 "전" 요율로
-- 계산해야 한다(사용자 명시 요구). 그래서 최신값 하나만 남기지 않고
-- (vendor_item_id, captured_at) 단위로 쌓아서, 조회 시점(sale_date)보다 이전인
-- 가장 최근 스냅샷을 골라 쓴다 — web/CLAUDE.md의 상품/옵션별 상세표 계산 참조.
--
-- trigger_source: 지금은 항상 'manual_refresh'(수동 "상품 원가정보 갱신" 버튼)뿐이지만,
-- 나중에 웹에 가격 수정 기능이 생기면 가격 변경 직후 자동으로 그 상품만 스냅샷을
-- 찍는 'price_change' 트리거가 추가될 예정이라 컬럼을 미리 마련해둔다(2026-08-16 결정).
-- ============================================================

create table if not exists rocket_growth_item_cost_snapshots (
  id                          bigint generated by default as identity primary key,
  vendor_item_id              text not null,
  captured_at                 timestamptz not null default now(),
  commission_amount           bigint not null,  -- 개당 판매수수료 (takeRateAmount)
  fulfillment_amount          bigint not null,  -- 개당 입출고비 (fulfillmentFee+warehousingFee 합)
  monthly_storage_fee_amount  bigint not null default 0,  -- 스냅샷 시점 기준 이번 달 누적보관비
  trigger_source              text not null default 'manual_refresh'
);

create unique index if not exists rocket_growth_item_cost_snapshots_vid_captured_at
  on rocket_growth_item_cost_snapshots (vendor_item_id, captured_at);

-- 특정 날짜 이전 최신 스냅샷 조회용(as-of 조인 패턴)
create index if not exists rocket_growth_item_cost_snapshots_vid_captured_at_desc
  on rocket_growth_item_cost_snapshots (vendor_item_id, captured_at desc);

alter table rocket_growth_item_cost_snapshots enable row level security;

drop policy if exists "read_for_authenticated" on rocket_growth_item_cost_snapshots;
create policy "read_for_authenticated" on rocket_growth_item_cost_snapshots
  for select to authenticated using (true);

drop policy if exists "write_for_admin" on rocket_growth_item_cost_snapshots;
create policy "write_for_admin" on rocket_growth_item_cost_snapshots
  for all to authenticated
  using (is_admin()) with check (is_admin());
