-- ============================================================
-- 015. 상품원장 — 내 SKU 마스터 (시스템 전체의 축)
--
-- 왜 필요한가: 지금까지 이 DB엔 "남의 상품"(products/product_items, 소싱 조사용)과
-- "내 판매실적"(rocket_growth_*)만 있고, **"내 상품"이라는 개념이 없다.** 그래서
-- 매입원가를 어디에도 붙일 수 없고, 순이익 공식에 COGS가 빠져 있다
-- (docs/decisions.md 2026-08-18).
--
-- 식별자를 왜 바코드로 잡았나 (2026-08-18 확정, 절대 바꾸지 말 것):
--   쿠팡이 발급한 바코드 = 로켓그로스 입고용 바코드 = 쿠플러스 구매요청에 입력하는 값
--   = 구매대행 청구서 PDF에 찍혀 나오는 값 = 배대지가 물리적으로 부착하는 값.
--   발주·청구서·창고·쿠팡이 전부 같은 번호를 쓰는 유일한 값이라, 이걸 조인키로 쓰면
--   청구서 파싱이 100% 정확해진다. 상품명 텍스트 매칭은 수백 개만 넘어도 반드시 깨진다.
--   단 바코드는 쿠팡이 준 값이라 채널 종속적이므로, PK는 내부 uuid로 두고
--   바코드는 unique 자연키로만 쓴다(나중에 스마트스토어 등 추가 대비).
--
-- 채널 매핑을 별도 테이블(sku_channel_listings)로 뺀 이유:
--   my_skus에 coupang_vendor_item_id를 직접 박으면 채널이 늘 때 전면 수술이 된다.
--   사용자가 "나중에 다른 채널도 계획 있다"고 명시(2026-08-18).
-- ============================================================

-- ── 내 상품 (쿠팡 "등록상품" 단위) ────────────────────────────
create table if not exists my_products (
  id                 uuid primary key default gen_random_uuid(),
  name               text not null,
  status             text not null default 'active',   -- active | paused | discontinued
  category_hint      text,                             -- 쿠팡 카테고리명(수수료 매칭용, 자유 텍스트)
  memo               text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

-- ── 내 SKU (옵션 단위) — 시스템 전체의 축 ★ ──────────────────
create table if not exists my_skus (
  id                    uuid primary key default gen_random_uuid(),
  product_id            uuid references my_products(id) on delete cascade,

  barcode               text,       -- 쿠팡 발급. 실무 조인키. NULL 허용(샘플 등 NOBARCODE 예외)
  sku_name              text not null,  -- 쿠팡 상품명+옵션명 = 쿠플러스에 입력하는 값과 동일해야 함

  sku_type              text not null default 'single',  -- single | set
  -- 반품 SKU: 로켓그로스는 반품건에 별도 옵션ID를 부여한다. 상품명은 원본과 같고
  -- WING 재고현황 화면엔 '반품-최상' 배지가 붙는데, 그 배지 필드가 우리가 저장 중인
  -- inventory-health-dashboard 응답에 있는지는 아직 미확인(2026-08-18).
  -- 지금은 자리만 만들어두고, 재고 페이지 작업 때 API 재캡처해서 자동 판별을 붙인다.
  sku_kind              text not null default 'normal',  -- normal | return
  return_of_sku_id      uuid references my_skus(id),     -- 반품 SKU면 원본 SKU

  status                text not null default 'active',  -- active | paused | liquidating | discontinued

  -- 발주 파라미터
  moq                   int,                 -- 최소주문수량. SKU마다 다르고 같은 상품도 판매자마다 다름
  moq_source            text default 'couplus',  -- couplus(1688 연동값 자동) | manual(수기 수정)
  lead_time_days        numeric,             -- 실측 리드타임. 발주 이력으로 자동 갱신 (초기값 14)
  safety_days           numeric default 5,   -- 안전재고 일수. SKU별로 유동 튜닝

  -- 쿠플러스 구매요청 시 매번 다시 입력하지 않으려고 SKU에 고정 저장 (2026-08-18 사용자 확인)
  packing_options       jsonb default '{"basic_inspection":true,"barcode_label":true}'::jsonb,

  -- 한글표시사항 (쿠플러스 요청서 9번 항목). SKU마다 고정값이라 여기 저장 후 자동 채움.
  -- 쿠팡 상품등록에도 상당 부분 공통으로 들어간다(사용자 확인).
  label_importer        text,   -- 수입원/판매원
  label_manufacturer    text,   -- 제조원
  label_origin_country  text,   -- 제조국
  label_volume          text,   -- 내용량
  label_material        text,   -- 원료명 및 성분명(재질)
  label_product_type    text,   -- 상품유형
  label_caution         text,   -- 사용시 주의사항
  label_usage_standard  text,   -- 사용기준

  -- 쿠팡이 제시하는 권장값. 지금 안 쌓으면 과거는 영영 복원 불가라 저장해둔다
  -- (나중에 "쿠팡 권장 대비 내 판단의 결과" 분석용, 2026-08-18 사용자 요청).
  coupang_recommended_price       bigint,
  coupang_recommended_inbound_qty int,
  coupang_recommendation_at       timestamptz,

  sourcing_decision_id  uuid,    -- 017에서 FK 추가 (소싱 판단 → SKU 추적)
  memo                  text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- 바코드는 있을 때만 유니크 (NOBARCODE 예외를 허용하면서 중복은 막는다)
create unique index if not exists my_skus_barcode_uniq
  on my_skus (barcode) where barcode is not null;
create index if not exists my_skus_product_id on my_skus (product_id);
create index if not exists my_skus_status on my_skus (status);

-- ── 채널별 판매 매핑 (채널 독립 구조의 핵심) ──────────────────
create table if not exists sku_channel_listings (
  id                 bigint generated by default as identity primary key,
  sku_id             uuid not null references my_skus(id) on delete cascade,
  channel            text not null default 'coupang_rg',  -- coupang_rg | coupang_3p | smartstore | ...
  external_option_id text,     -- 쿠팡이면 vendor_item_id (= rocket_growth_* 조인키)
  external_product_id text,    -- 쿠팡이면 seller_product_id (등록상품ID)
  listing_url        text,
  is_active          boolean not null default true,
  created_at         timestamptz not null default now()
);
create unique index if not exists sku_channel_listings_uniq
  on sku_channel_listings (channel, external_option_id) where external_option_id is not null;
create index if not exists sku_channel_listings_sku on sku_channel_listings (sku_id);

-- ── 1688 공급처 (같은 SKU를 여러 판매자에게서 살 수 있음) ─────
create table if not exists sku_suppliers (
  id               bigint generated by default as identity primary key,
  sku_id           uuid not null references my_skus(id) on delete cascade,
  seller_1688_id   text,
  offer_url        text,          -- https://detail.1688.com/offer/{offerId}.html
  offer_id         text,
  -- 쿠플러스 구매요청 화면에서 고르는 중국어 옵션명. 저장해두면 재발주 시 그대로 재사용.
  option1_cn       text,
  option2_cn       text,
  moq              int,
  last_price_cny   numeric,
  last_ordered_at  timestamptz,
  defect_note      text,          -- 불량 이력 (공급처 평가용)
  is_primary       boolean not null default false,
  created_at       timestamptz not null default now()
);
create index if not exists sku_suppliers_sku on sku_suppliers (sku_id);

-- ── 세트 구성 (BOM) ──────────────────────────────────────────
-- 사용자 확인(2026-08-18): 세트는 중국에서 낱개로 사서 배대지에서 묶어 포장한다.
-- 묶음 하나에 바코드 하나만 붙으므로 세트도 그냥 별개 SKU다. 다만 원가는
-- 구성품 원가의 합으로 계산해야 하고, "따로따로도 알 수 있게" 해달라는 요구가 있었다.
-- 구성품을 단품으로도 팔 가능성이 있다고 해서(대체로 안 팔지만) 재고를 나눠 쓰는
-- 케이스를 허용하는 구조로 둔다.
create table if not exists sku_bom (
  set_sku_id       uuid not null references my_skus(id) on delete cascade,
  component_sku_id uuid not null references my_skus(id),
  qty              int not null default 1,
  primary key (set_sku_id, component_sku_id)
);

-- ── RLS (기존 테이블들과 동일 패턴) ──────────────────────────
do $$
declare t text;
begin
  foreach t in array array['my_products','my_skus','sku_channel_listings','sku_suppliers','sku_bom']
  loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "read_for_authenticated" on %I', t);
    execute format('create policy "read_for_authenticated" on %I for select to authenticated using (true)', t);
    execute format('drop policy if exists "write_for_admin" on %I', t);
    execute format('create policy "write_for_admin" on %I for all to authenticated using (is_admin()) with check (is_admin())', t);
  end loop;
end $$;
