-- ============================================================
-- 016. 공급 — 발주·로트·원가·재고·매출원가(COGS)
--
-- 구조 근거는 docs/decisions.md 2026-08-18 절 전체. 요약하면:
--   · 국제운임·통관비는 별도 청구가 아니라 **환율에 포함**돼 있다 → 컨테이너 운임
--     SKU 배분 문제가 아예 없다. 다시 설계하지 말 것.
--   · 환율은 두 종류(구매대행 310, 작업비 219.72)이고 주문 생성 시각에 고정된다
--     → 로트마다 박아둔다. "현재 환율" 하나만 들고 있으면 안 된다.
--   · 원가는 발주 시점에 사실상 확정된다 → **소급 재계산 로직을 만들지 말 것.**
--     선입선출로 로트별 확정 원가를 물려두고 팔린 순서대로 차감하면 끝.
--   · 재고 위치가 3곳(중국창고/운송중/쿠팡). 중국 창고 잔량은 쿠플러스에서 볼 수
--     없어서 `발주수량 − 한국으로 보낸 수량`으로 우리가 직접 계산한다.
-- ============================================================

-- ── 쿠플러스 고시 환율 이력 ──────────────────────────────────
-- 공지 팝업으로만 통보된다(2026-08-05: 320→310). 원문을 같이 남겨 근거를 추적 가능하게.
create table if not exists exchange_rates (
  id             bigint generated by default as identity primary key,
  effective_from timestamptz not null,
  rate_purchase  numeric not null,   -- 구매대행용(상품+중국내배송+국제운임+통관+수수료 포함)
  rate_work      numeric,            -- 작업비·배송비 정산용(실환율에 가까움)
  source         text default 'couplus_notice',
  notice_text    text,
  created_at     timestamptz not null default now()
);
create unique index if not exists exchange_rates_effective_from on exchange_rates (effective_from);

-- ── 구매요청 (쿠플러스 1건 = 구매대행 청구서 PDF 1장) ────────
create table if not exists purchase_orders (
  id                 uuid primary key default gen_random_uuid(),
  requested_at       timestamptz not null,
  status             text not null default 'requested',
  -- requested → invoiced → paid → ordered → arrived_china
  --   → inbound_requested → received (/ cancelled)

  rate_purchase      numeric,        -- 그 시점 환율을 박아둔다 ★
  rate_source        text,

  invoice_pdf_path   text,           -- 웹에 끌어다 놓은 PDF 보관 경로
  invoice_raw_text   text,           -- 파싱 원문 보존 (역추적용)
  parsed_at          timestamptz,
  parse_method       text,           -- regex | ai_assisted
  parse_confidence   numeric,
  confirmed_by_user  boolean not null default false,  -- 저장 전 사람 확인 단계 필수

  total_cny          numeric,
  total_krw          bigint,
  vat_krw            bigint,         -- 세금계산서 수취 시 매입세액(환급 대상) — 원가에 포함하지 말 것
  grand_total_krw    bigint,

  payment_method     text,           -- bank_transfer | deposit (둘 다 씀)
  paid_at            timestamptz,
  memo               text,
  created_at         timestamptz not null default now()
);
create index if not exists purchase_orders_status on purchase_orders (status);

-- ── 구매요청 줄 (PDF 한 줄 = SKU 1개) ────────────────────────
-- PDF 구조 함정(반드시 지킬 것, docs/decisions.md 2026-08-18):
--   · 줄이 "1688 주문 묶음"으로 그룹지어져 있고 배송비/총금액은 묶음 첫 줄에만 찍힌다
--   · 줄별 KRW가 없다 (전체 합계만 첫 줄에 한 번)
--   · 협상후 단가는 총액에서 역산된 소수점 5자리라 믿으면 안 된다 → 총금액 기준
create table if not exists purchase_order_lines (
  id                     bigint generated by default as identity primary key,
  po_id                  uuid not null references purchase_orders(id) on delete cascade,
  line_no                int,

  sku_id                 uuid references my_skus(id),
  barcode_text           text,      -- PDF 원문 (매칭 실패해도 원값 보존)
  product_name_text      text,      -- PDF 원문 상품명

  qty                    int not null,
  group_key              text,      -- 묶음 식별 (총금액이 찍힌 줄 기준으로 부여)
  unit_price_cny         numeric,   -- 협상후 단가 (참고용, 계산 기준 아님)
  group_shipping_cny     numeric,   -- 묶음 배송비 (묶음 첫 줄에만)
  group_total_cny        numeric,   -- 묶음 총금액 (계산 기준 ★)
  allocated_shipping_cny numeric,   -- 수량 비례 배분 결과 (유일하게 남은 배분 대상)

  line_cost_cny          numeric,
  line_cost_krw          bigint,

  cancelled_qty          int not null default 0,  -- 1688 재고없음 취소 대응
  cancel_reason          text,

  raw_line               jsonb,     -- PDF 원문 그대로 ★ (집계만 남기지 말 것 — 프로젝트 원칙)
  created_at             timestamptz not null default now()
);
create index if not exists po_lines_po on purchase_order_lines (po_id);
create index if not exists po_lines_sku on purchase_order_lines (sku_id);

-- ── 한국 입고 (제트 청구서 1장 = 한 번의 출고 묶음) ──────────
-- 청구서에 상품명이 없다. 대신 단가가 고정이라 개당으로 계산 가능:
--   입고분류/검수/포장 200원 + 바코드/원산지작업 100원 = 개당 300원
--   (실측: 89,400/447=200, 89,400/894=100)
-- 단 세트구성·특수요청이 붙으면 유동이라 extra_fee로 열어둔다.
create table if not exists inbound_shipments (
  id                    uuid primary key default gen_random_uuid(),
  requested_at          timestamptz,
  arrived_at            timestamptz,
  invoice_pdf_path      text,
  invoice_raw_text      text,
  confirmed_by_user     boolean not null default false,

  rate_work             numeric,   -- 작업비 정산 환율 (219.72 등)
  shipping_method       text,      -- milkrun_parcel | pallet | direct_parcel
  work_fee_total_krw    bigint,
  box_fee_krw           bigint default 0,
  storage_fee_krw       bigint default 0,   -- CBM당 300원/일, 2주 무료 (현재는 미청구)
  vat_krw               bigint,
  grand_total_krw       bigint,

  -- 밀크런 택배비는 쿠팡이 화주에게 직접 청구한다 — 이 청구서엔 안 나오는 별도 비용
  coupang_billed_shipping_krw bigint default 0,
  memo                  text,
  created_at            timestamptz not null default now()
);

create table if not exists inbound_shipment_lines (
  id                        bigint generated by default as identity primary key,
  shipment_id               uuid not null references inbound_shipments(id) on delete cascade,
  lot_id                    uuid,          -- 아래 inventory_lots (순환참조 회피로 FK 생략)
  sku_id                    uuid references my_skus(id),
  qty                       int not null,
  work_fee_per_unit_krw     numeric default 300,
  extra_fee_krw             numeric default 0,
  extra_fee_reason          text,          -- 세트구성/에어캡/봉제 등
  allocated_box_fee_krw     numeric default 0,
  allocated_storage_fee_krw numeric default 0,
  unit_extra_cost_krw       numeric        -- 이 입고로 로트 원가에 더해질 개당 금액
);
create index if not exists inbound_lines_shipment on inbound_shipment_lines (shipment_id);

-- ── 재고 로트 (선입선출의 단위) ★ ────────────────────────────
create table if not exists inventory_lots (
  id                  uuid primary key default gen_random_uuid(),
  sku_id              uuid not null references my_skus(id),
  po_line_id          bigint references purchase_order_lines(id),

  qty_ordered         int not null default 0,
  qty_china           int not null default 0,   -- 중국 배대지 창고 대기
  qty_transit         int not null default 0,   -- 한국행 운송중
  qty_coupang         int not null default 0,   -- 쿠팡 물류센터 (판매 가능)
  qty_sold            int not null default 0,
  qty_disposed        int not null default 0,

  unit_cost_krw       numeric,                  -- 최종 개당 원가 (부가세 제외 ★)
  cost_status         text not null default 'estimated',  -- estimated | confirmed

  -- 원자적 raw 보존 (프로젝트 원칙: 집계만 저장하고 원본 버리면 역추적 불가)
  --   { cny_unit, cny_shipping_alloc, rate_purchase,
  --     work_fee, box_fee, storage_fee, rate_work }
  cost_breakdown      jsonb,

  ordered_at          timestamptz,
  arrived_china_at    timestamptz,
  arrived_coupang_at  timestamptz,              -- FIFO 정렬 기준
  created_at          timestamptz not null default now()
);
create index if not exists inventory_lots_sku_fifo
  on inventory_lots (sku_id, arrived_coupang_at);

-- ── 재고 증감 이력 (모든 변화를 한 곳에) ─────────────────────
create table if not exists inventory_movements (
  id           bigint generated by default as identity primary key,
  lot_id       uuid references inventory_lots(id),
  sku_id       uuid not null references my_skus(id),
  type         text not null,   -- inbound | china_to_kr | sale | return_restore
                                -- | dispose | set_consume | cancel
  qty          int not null,    -- 음수 가능 (반품 복원 등)
  occurred_at  timestamptz not null,
  ref_table    text,
  ref_id       text,
  memo         text,
  created_at   timestamptz not null default now()
);
create index if not exists inventory_movements_sku_date on inventory_movements (sku_id, occurred_at);

-- ── 매출원가 배분 (판매 ↔ 로트 연결, FIFO 결과) ──────────────
-- WING 일별 판매수량은 순수량(반품 시 음수)이고, 순수량 0인 옵션은 목록에서 아예
-- 빠진다(migrations/009 + docs/api-notes.md 4-4-2). 그래서 순수량으로 FIFO를 돌리면
-- 반품 복원이 자동으로 맞아떨어진다 — 별도 반품 처리 로직을 만들지 말 것.
create table if not exists cogs_allocations (
  id             bigint generated by default as identity primary key,
  sale_date      date not null,
  sku_id         uuid not null references my_skus(id),
  vendor_item_id text,          -- 판매현황 원본 조인키 (추적용)
  lot_id         uuid references inventory_lots(id),
  qty            int not null,  -- 음수 가능 (반품)
  unit_cost_krw  numeric not null,
  total_cost_krw numeric not null,
  created_at     timestamptz not null default now()
);
create index if not exists cogs_allocations_date_sku on cogs_allocations (sale_date, sku_id);

-- ── 예치금 (불량 환불이 여기로 들어온다) ─────────────────────
-- 잔액은 대행사가 **사진으로만** 통보한다 → 수기 입력값과 시스템 계산값을 나란히 두고
-- 차이가 나면 화면에서 경고한다.
create table if not exists supplier_deposits (
  id                    bigint generated by default as identity primary key,
  occurred_at           timestamptz not null,
  type                  text not null,   -- charge | spend | refund
  amount_krw            bigint not null,
  balance_manual_krw    bigint,          -- 사진 보고 입력한 실제 잔액
  balance_computed_krw  bigint,          -- 시스템 계산 잔액
  po_id                 uuid references purchase_orders(id),
  memo                  text,
  created_at            timestamptz not null default now()
);

do $$
declare t text;
begin
  foreach t in array array['exchange_rates','purchase_orders','purchase_order_lines',
                           'inbound_shipments','inbound_shipment_lines','inventory_lots',
                           'inventory_movements','cogs_allocations','supplier_deposits']
  loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "read_for_authenticated" on %I', t);
    execute format('create policy "read_for_authenticated" on %I for select to authenticated using (true)', t);
    execute format('drop policy if exists "write_for_admin" on %I', t);
    execute format('create policy "write_for_admin" on %I for all to authenticated using (is_admin()) with check (is_admin())', t);
  end loop;
end $$;
