-- ============================================================
-- 024. 쿠팡 판매가·판매여부·재고를 시스템이 갖는다
--
-- 왜 필요했나(2026-08-20 발견): **이 시스템은 쿠팡 판매가를 몰랐다.**
-- 판매현황이 쓰는 값은 `매출 ÷ 수량`으로 역산한 평균 실현가(web/js/20-sales.js)라
--   ① 안 팔린 SKU는 가격을 알 수 없고
--   ② 팔린 것도 쿠폰이 섞인 값이지 '등록 판매가'가 아니다
-- 상품원장에서 "현재 7,500원 → 얼마로"를 보여주려면 등록가 자체가 있어야 한다.
--
-- 읽는 경로는 정찰로 확인됐다(2026-08-20 실물 호출):
--   GET /v2/providers/seller_api/apis/api/v1/marketplace/vendor-items/{id}/inventories
--   → { amountInStock: 24, salePrice: 7500, onSale: true, sellerItemId: ... }
-- 옵션 단건 조회(vendor-items/{id}) 자체는 404다. 이 하위 경로만 살아 있다.
-- ============================================================

-- ── 최신값: 화면이 목록을 그릴 때 바로 읽는다 ────────────────
-- 레지스트리는 이미 vendor_item_id가 PK라 옵션 하나에 한 행이다. 여기 붙이는 게 맞다.
-- originalPrice(할인 전 정가)는 일부러 안 넣는다 — /inventories가 안 주는 값이라
-- 채울 수 없는 컬럼을 만들면 "비어 있음"과 "아직 안 읽음"을 구분 못 하게 된다.
alter table rocket_growth_product_registry
  add column if not exists sale_price       bigint;    -- 현재 판매가(원)
alter table rocket_growth_product_registry
  add column if not exists on_sale          boolean;   -- 판매중 여부
alter table rocket_growth_product_registry
  add column if not exists amount_in_stock  int;       -- 쿠팡 물류센터 재고
-- **언제 읽은 값인지**를 반드시 같이 둔다. 이게 없으면 화면이 "가격 없음"과
-- "아직 한 번도 안 읽음"을 구분 못 한다 — 파생 화면은 원본 부재를 말해야 한다(R-15).
alter table rocket_growth_product_registry
  add column if not exists price_checked_at timestamptz;

-- ── 변동 이력: 값이 **바뀌었을 때만** 1행 ────────────────────
-- coupang_write_queue(023)도 이력이지만 그건 '우리가 바꾼 것'만 남는다.
-- WING에서 사람이 직접 바꾸거나 쿠팡이 자동으로 조정한 건 거기 안 남는다.
-- 이 표가 있어야 **누가 바꿨든** 가격 궤적이 이어지고, 나중에 판매량과 겹쳐서
-- "가격을 내렸더니 어떻게 됐나"를 볼 수 있다(이 프로젝트의 장기 방향: AI 분석).
--
-- 매번 넣지 않고 바뀔 때만 넣는 이유: 하루 1회 x SKU 수천 개면 대부분이 같은 값의
-- 반복이고, 그러면 "언제 바뀌었나"를 찾기 위해 매번 이전 행과 비교해야 한다.
-- 바뀐 것만 넣으면 이 표를 읽는 것 자체가 곧 변경 목록이 된다.
create table if not exists rocket_growth_item_price_history (
  id               bigint generated by default as identity primary key,
  vendor_item_id   text not null,
  changed_at       timestamptz not null default now(),

  sale_price       bigint,
  prev_sale_price  bigint,     -- 바로 이전 값. 이걸 같이 둬야 한 행만 봐도 변화가 읽힌다
  on_sale          boolean,
  prev_on_sale     boolean,

  -- 이 변경이 어디서 왔나. **가장 값진 정보다** —
  -- our_write: 우리 시스템이 바꿈(write_queue_id로 그때의 판단 근거까지 따라갈 수 있다)
  -- sync     : 동기화가 '어느새 달라져 있는 것'을 발견함 = WING에서 사람이 바꿨거나 쿠팡이 조정함
  source           text not null default 'sync' check (source in ('sync', 'our_write')),
  write_queue_id   uuid references coupang_write_queue(id)
);

create index if not exists rg_item_price_history_item
  on rocket_growth_item_price_history (vendor_item_id, changed_at desc);

do $$
begin
  execute 'alter table rocket_growth_item_price_history enable row level security';
  execute 'drop policy if exists "read_for_authenticated" on rocket_growth_item_price_history';
  execute 'create policy "read_for_authenticated" on rocket_growth_item_price_history for select to authenticated using (true)';
  execute 'drop policy if exists "write_for_admin" on rocket_growth_item_price_history';
  execute 'create policy "write_for_admin" on rocket_growth_item_price_history for all to authenticated using (is_admin()) with check (is_admin())';
end $$;

-- ── 웹의 '가격 새로고침' 버튼을 위한 큐 종류 추가 ────────────
-- 웹은 VPS를 직접 못 부른다(고정 IP 문제, D-16). 그래서 가격 재조회도 같은 통로를 쓴다 —
-- 웹이 여기 한 행 넣으면 워커가 집어서 쿠팡에 물어보고 registry를 갱신한다.
-- 통로를 하나로 두면 "웹이 시킨 일"의 성공·실패가 전부 한 표에 남는다.
alter table coupang_write_queue drop constraint if exists coupang_write_queue_kind_check;
alter table coupang_write_queue add constraint coupang_write_queue_kind_check
  check (kind in ('price', 'sale_stop', 'sale_resume', 'price_sync'));

-- price_sync는 대상이 없으면 '전체'라는 뜻이다. 반면 가격 변경에 대상이 없으면
-- 그건 사고다 — 어느 상품 가격을 바꿀지 모르는 채로 실행될 수 있다.
-- 그래서 NOT NULL을 푸는 대신, 종류별로 다르게 강제한다.
alter table coupang_write_queue alter column vendor_item_id drop not null;
alter table coupang_write_queue drop constraint if exists coupang_write_queue_target_required;
alter table coupang_write_queue add constraint coupang_write_queue_target_required
  check (kind = 'price_sync' or vendor_item_id is not null);
