-- ============================================================
-- 026. 상품 변경 이력 + 일별 옵션 지표
--
-- 목적 하나로 묶인 두 표다: **"이렇게 바꿨더니 어떻게 됐나"를 나중에 AI가 답하게 하는 것.**
-- 그러려면 (1) 무엇을 언제 왜 바꿨는지 (2) 그 전후의 성과 가 둘 다 있어야 한다.
-- 지금은 둘 다 없다 — 상품 정보는 바꾸면 product_json을 덮어써서 이전 값이 사라지고,
-- 노출·클릭 지표는 어느 테이블에도 없다.
--
-- **이건 시간이 지나면 복구가 안 되는 종류다.** 오늘 바꾼 썸네일이 뭐였는지는
-- 내일이면 알 방법이 없다. 그래서 다른 기능보다 먼저 넣는다.
-- ============================================================

-- ── 1. 상품 변경 이력 ────────────────────────────────────────
-- coupang_write_queue(023)에 sent_body가 있지만 그건 '요청 로그'지 '실험 기록'이 아니다.
-- 통짜 JSON을 AI에게 파헤치게 하면 매번 다르게 해석하고 결과가 흔들린다.
-- **바꾼 항목을 field로 정규화하는 게 이 표의 핵심이다** —
-- 그래야 "썸네일을 바꾼 사례를 전부 모아 전후를 비교해줘"가 한 줄 SQL이 된다.
create table if not exists product_change_history (
  id                bigint generated by default as identity primary key,
  vendor_item_id    text not null,            -- 로켓그로스 옵션ID. 지표 표와 같은 조인키다
  seller_product_id text,
  sku_id            uuid references my_skus(id),
  changed_at        timestamptz not null default now(),

  -- 무엇을 바꿨나. **한 요청에서 두 가지를 바꿨으면 두 행이 된다.**
  -- 그래야 "썸네일만 바꾼 경우"와 "썸네일+가격을 같이 바꾼 경우"를 나눠 볼 수 있다
  -- (섞인 변경은 원인을 못 가린다 — 분석에서 제외해야 할 사례를 찾으려면 쪼개져 있어야 한다).
  field             text not null check (field in (
                      'thumbnail', 'detail_page', 'search_tags',
                      'product_name', 'item_name', 'price', 'sale_status')),
  before_value      jsonb,   -- 바꾸기 직전 값. 워커가 쿠팡에서 조회한 **실제** 값이다
  after_value       jsonb,

  -- our_write: 우리가 바꿈 / sync: 어느새 달라져 있는 걸 발견함(WING에서 사람이 바꿨거나 쿠팡이 조정)
  source            text not null default 'our_write' check (source in ('our_write', 'sync')),

  -- **이 변경으로 무엇이 움직여야 하는가.** 지표가 깔때기 단계별로 있어서
  -- 바꾼 것에 따라 봐야 할 지표가 다르다(2026-08-20 실측 데이터로 확인):
  --   thumbnail/search_tags/product_name → views, visitors  (유입이 움직여야 맞다)
  --   detail_page                        → conversion_rate, cart_adds (조회는 안 변해야 정상)
  --   price                              → conversion_rate, item_winner_rate
  -- 이걸 행마다 박아두면 **AI가 "무엇을 봐야 하는지"를 추측하지 않는다.**
  -- 썸네일을 바꿨는데 전환율만 보면 아무 결론도 못 낸다.
  primary_metrics   text[],

  -- 왜 바꿨나. 사람이 적는다. 나중에 AI가 "이 가설이 맞았나"를 판정할 근거가 된다.
  -- 메모가 아니라 **가설**로 받는 게 핵심이다 — "그냥 바꿔봄"과 "썸네일이 어두워서
  -- 눈에 안 띈다고 봤다"는 나중에 학습할 수 있느냐가 완전히 다르다.
  hypothesis        text,
  changed_by        uuid,
  queue_id          uuid references coupang_write_queue(id)
);

create index if not exists product_change_history_item
  on product_change_history (vendor_item_id, changed_at desc);
create index if not exists product_change_history_field
  on product_change_history (field, changed_at desc);

-- ── 2. 일별 옵션 지표 (WING 비즈니스 인사이트 엑셀) ──────────
-- 출처: WING > 비즈니스 인사이트 > 상품별 지표 엑셀 다운로드.
-- **당일 데이터는 다음날 밤에 채워진다** — 어제치부터 받을 수 있다(사용자 확인).
--
-- 실물 확인(2026-08-20, 48행):
--   조인키가 이미 우리 것과 같다 — '옵션 ID' = vendor_item_id, '등록상품ID' = seller_product_id
--   **엑셀의 모든 셀이 문자열이다.** 숫자도 문자열이고, 아이템위너 비율은
--   "88.900000000000005684341886080801486968994140625" 처럼 온다. 반드시 변환·반올림할 것.
--   검산: 매출 = 총매출 + 취소금액, 판매량 = 총판매수 + 취소수 (둘 다 정확히 일치)
--   검산: 구매전환율 = 주문 ÷ **조회** (방문자가 아니다. 6건 소수점까지 일치)
create table if not exists coupang_item_metrics_daily (
  -- 하루치를 올린다. WING에서 기간을 넓게 잡아 받으면 그 기간 합계가 오는데,
  -- 그러면 일별 시계열이 깨진다 — 화면에서 하루만 고르도록 막고, 판매량을
  -- rocket_growth_sales_daily와 대조해 어긋나면 경고한다.
  metric_date        date not null,
  vendor_item_id     text not null,
  seller_product_id  text,

  -- 엑셀이 주는 이름·분류. 우리 my_skus와 다를 수 있어 그대로 남긴다(R-04) —
  -- 이름이 언제 바뀌었는지가 이 컬럼에 자연스럽게 기록된다.
  item_name          text,
  product_name       text,
  category           text,
  sales_method       text,      -- 로켓그로스 | 판매자배송

  -- 순값(취소 차감 후)
  revenue            bigint,
  orders             int,
  sold_qty           int,

  -- **깔때기.** 이 셋이 이 표의 존재 이유다 — 지금까지 시스템에 없던 값이다.
  visitors           int,       -- 방문자
  views              int,       -- 조회 (전환율의 분모)
  cart_adds          int,       -- 장바구니
  conversion_rate    numeric,   -- 주문/조회 (%). 엑셀이 준 값을 그대로 담는다

  -- 아이템위너를 못 잡으면 노출 자체가 안 된다. **실험의 최대 교란 요인이다** —
  -- 위너를 뺏긴 기간의 지표 변화는 내가 뭘 바꿔서가 아니다.
  -- 실측에서 12.1%·66.4%·0%인 옵션들이 있었다.
  item_winner_rate   numeric,

  -- 총값(취소 전) + 취소. 순값과 나란히 둬야 "얼마나 취소됐나"가 보인다(R-04·R-05)
  total_revenue      bigint,
  total_sold_qty     int,
  cancel_amount      bigint,
  cancel_qty         int,
  instant_cancel_qty int,

  uploaded_at        timestamptz not null default now(),
  primary key (metric_date, vendor_item_id)
);

create index if not exists coupang_item_metrics_date
  on coupang_item_metrics_daily (metric_date desc);

do $$
declare t text;
begin
  foreach t in array array['product_change_history', 'coupang_item_metrics_daily']
  loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "read_for_authenticated" on %I', t);
    execute format('create policy "read_for_authenticated" on %I for select to authenticated using (true)', t);
    execute format('drop policy if exists "write_for_admin" on %I', t);
    execute format('create policy "write_for_admin" on %I for all to authenticated using (is_admin()) with check (is_admin())', t);
  end loop;
end $$;

-- ── 큐에 가설을 적을 자리 ────────────────────────────────────
-- 이미 reason 컬럼이 있지만 그건 "왜 이 가격으로"였다. 상품 변경은 실험이라
-- 기대하는 결과까지 받아야 나중에 맞았는지 판정할 수 있다.
alter table coupang_write_queue
  add column if not exists hypothesis text;
