-- ============================================================
-- 039. 구매요청 — 청구서 앞에 있던 빈 칸을 메운다
--
-- 지금까지 시스템은 **청구서부터** 시작했다(purchase_orders 1단계 = "청구서 수령").
-- 그 앞의 구매요청은 쿠플러스 웹에서 사람이 치고 **어디에도 안 남았다.**
-- 그래서 "요청한 것"과 "온 청구서"를 맞춰볼 근거가 없었다 —
-- 요청했는데 청구서가 안 왔는지, 수량이 깎여서 왔는지 알 방법이 없다.
--
-- 단위가 두 개다(2026-08-22 캡처로 확정):
--   쿠플러스 요청 1건 = **SKU 1개**(옵션 하나)   → purchase_request_lines
--   구매대행 청구서 1장 = **여러 요청을 묶은 것** → purchase_orders (016)
-- 그래서 요청 줄을 묶는 자리(purchase_requests)를 두고, 그 묶음이 청구서를 가리킨다.
-- 016의 purchase_orders 를 재사용하지 않는 이유가 여기 있다 — 단위가 다르다.
--
-- 폼 전체는 docs/api/couplus.md 「구매요청 폼」에 캡처 그대로 적혀 있다.
-- ============================================================

-- ── 요청 묶음 (한 번에 쿠플러스에 넣는 단위) ────────────────
create table if not exists purchase_requests (
  id            uuid primary key default gen_random_uuid(),
  title         text,                                  -- "2026-08-22 요청분"
  status        text not null default 'draft',
  -- draft(만드는 중) → submitted(쿠플러스에 넣음) → invoiced(청구서 받음) / cancelled
  submitted_at  timestamptz,

  -- 청구서와 잇는 자리. **요청과 청구서는 1:1이 아닐 수 있다** — 쿠플러스가 묶어서
  -- 보내거나 나눠서 보낼 수 있으므로 nullable 로 두고 사람이 잇는다.
  po_id         uuid references purchase_orders(id) on delete set null,

  memo          text,
  created_by    uuid,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists purchase_requests_status on purchase_requests (status);
create index if not exists purchase_requests_po on purchase_requests (po_id);

-- ── 요청 줄 = 쿠플러스 요청 1건 = SKU 1개 ───────────────────
create table if not exists purchase_request_lines (
  id            bigint generated by default as identity primary key,
  request_id    uuid not null references purchase_requests(id) on delete cascade,
  sku_id        uuid references my_skus(id) on delete set null,

  -- **그때의 모습을 박아둔다**(R-04). SKU 이름·바코드·공급처는 나중에 바뀐다.
  -- 바뀌고 나면 "그때 무엇을 요청했나"를 복원할 방법이 없다.
  barcode_text    text,
  sku_name_text   text,
  offer_url       text,
  option1_cn      text,
  option2_cn      text,

  -- 수량. 계산이 제안한 값과 사람이 정한 값을 **둘 다** 남긴다 —
  -- 나중에 "내 감과 계산 중 무엇이 맞았나"를 보려면 둘 다 있어야 한다(R-05와 같은 생각).
  qty            int not null,
  qty_suggested  int,
  qty_reason     jsonb,      -- { daily_avg, lead_time, safety, on_hand, moq, verdict }

  -- 모달 1~4
  sale_bundle_qty int not null default 1,      -- 2. 판매구성수량
  is_bundle       boolean not null default false, -- 3. A-B번들 묶음구성여부
  destination     text not null default 'coupang_center',  -- 4. 도착지

  -- 모달 8. 검수 및 포장
  packing_method  text not null default 'delegate',
  -- delegate(포장 방법 위임·기본) | no_repack(재포장 생략) | opp(투명 OPP) | ldpe(불투명 LDPE)
  packing_options jsonb not null default
    '{"basic_inspection":true,"barcode_label":true,"cn_masking":false,"aircap":false,
      "origin_sewing":false,"origin_stamp":false,"origin_tag":false}'::jsonb,
  -- 기본검수 ₩200 + 바코드라벨 ₩100 = **개당 300원**. 제트 청구서 역산값과 일치한다.
  -- origin_* 는 6,000원/시간이라 켜지면 개당 300원 공식이 깨진다(extra_fee 로 간다).

  -- 기타요청사항 자유 텍스트 두 칸
  warehouse_note  text,       -- 배대지 작업요청사항
  seller_note     text,       -- 1688판매자와의 협의 사항

  -- 이 줄을 쿠플러스 화면에 실제로 옮겨 넣었나. 줄마다 따로 본다 —
  -- 한 묶음을 나눠서 넣다 끊기는 일이 실제로 생긴다.
  entered_at     timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists purchase_request_lines_req on purchase_request_lines (request_id);
create index if not exists purchase_request_lines_sku on purchase_request_lines (sku_id);

do $$
begin
  alter table purchase_requests drop constraint if exists purchase_requests_status_check;
  alter table purchase_requests add constraint purchase_requests_status_check
    check (status in ('draft', 'submitted', 'invoiced', 'cancelled'));

  alter table purchase_request_lines drop constraint if exists purchase_request_lines_dest_check;
  alter table purchase_request_lines add constraint purchase_request_lines_dest_check
    check (destination in ('coupang_center', 'owner'));

  alter table purchase_request_lines drop constraint if exists purchase_request_lines_packing_check;
  alter table purchase_request_lines add constraint purchase_request_lines_packing_check
    check (packing_method in ('delegate', 'no_repack', 'opp', 'ldpe'));
end $$;

-- ── RLS (다른 표와 같은 규칙) ────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array['purchase_requests', 'purchase_request_lines']
  loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "read_for_authenticated" on %I', t);
    execute format('create policy "read_for_authenticated" on %I for select to authenticated using (true)', t);
    execute format('drop policy if exists "write_for_admin" on %I', t);
    execute format('create policy "write_for_admin" on %I for all to authenticated using (is_admin()) with check (is_admin())', t);

    execute format('drop trigger if exists %I on %I', t || '_touch', t);
    execute format('create trigger %I before update on %I for each row execute function touch_updated_at()',
                   t || '_touch', t);
  end loop;
end $$;
